# Generated by Django 4.2.13 on 2026-07-15 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mlearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlearn_id', models.CharField(blank=True, max_length=250)),
                ('mlearn_name', models.CharField(blank=True, max_length=250)),
                ('mlearn_method', models.CharField(blank=True, default='linear_regression', max_length=250)),
                ('parameters', models.JSONField(default=dict)),
                ('test', models.CharField(blank=True, max_length=250)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
            },
        ),
    ]
