# Generated by Django 4.2.13 on 2026-07-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_tour',
            field=models.BooleanField(default=False),
        ),
    ]
