# Generated by Django 4.2.13 on 2026-07-15 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fmea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmea_name', models.CharField(blank=True, max_length=255)),
                ('fmea_sheetid', models.CharField(blank=True, max_length=255)),
                ('sheet_data', models.JSONField(default=list)),
                ('parameters', models.TextField(blank=True, default='')),
                ('process_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FMEA Sheet',
                'verbose_name_plural': 'FMEA Sheets',
            },
        ),
    ]
