# Generated by Django 2.1 on 2020-08-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlearn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlearn',
            name='mlearn_calculated_value',
        ),
    ]
