# Generated by Django 4.1 on 2022-10-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlearn', '0002_remove_mlearn_mlearn_calculated_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlearn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mlearn',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
    ]
