# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-01 10:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_name', models.CharField(max_length=255)),
                ('dataset_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('document', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('process_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='process.Process')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload.Dataset')),
                ('p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='process.Process')),
                ('u_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
