# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-01 10:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistical_id', models.CharField(blank=True, max_length=250)),
                ('statistical_name', models.CharField(blank=True, max_length=250)),
                ('statistical_method', models.CharField(blank=True, max_length=250)),
                ('statistical_calculated_value', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('test', models.CharField(blank=True, max_length=250)),
                ('dataset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.Dataset')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
