# Generated by Django 4.1 on 2022-10-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical', '0003_hypothetical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytical',
            name='analytical_calculated_value',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analytical',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='analytical',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='hypothetical',
            name='hypothetical_calculated_value',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='hypothetical',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hypothetical',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='statistical',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statistical',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='statistical',
            name='statistical_calculated_value',
            field=models.JSONField(default=dict),
        ),
    ]
