# Generated by Django 4.2.13 on 2026-07-15 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_id', models.CharField(blank=True, max_length=250)),
                ('visualization_name', models.CharField(blank=True, max_length=250)),
                ('type', models.CharField(blank=True, max_length=250)),
                ('parameters', models.JSONField(default=dict)),
                ('dataset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='statistical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistical_id', models.CharField(blank=True, max_length=250)),
                ('statistical_name', models.CharField(blank=True, max_length=250)),
                ('statistical_method', models.CharField(blank=True, max_length=250)),
                ('statistical_calculated_value', models.JSONField(default=dict)),
                ('parameters', models.JSONField(default=dict)),
                ('test', models.CharField(blank=True, max_length=250)),
                ('dataset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hypothetical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypothetical_id', models.CharField(blank=True, max_length=250)),
                ('hypothetical_name', models.CharField(blank=True, max_length=250)),
                ('hypothetical_method', models.CharField(blank=True, max_length=250)),
                ('hypothetical_calculated_value', models.JSONField(default=dict)),
                ('parameters', models.JSONField(default=dict)),
                ('test', models.CharField(blank=True, max_length=250)),
                ('dataset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='analytical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytical_id', models.CharField(blank=True, max_length=250)),
                ('analytical_name', models.CharField(blank=True, max_length=250)),
                ('analytical_method', models.CharField(blank=True, max_length=250)),
                ('analytical_calculated_value', models.JSONField(default=dict)),
                ('parameters', models.JSONField(default=dict)),
                ('test', models.CharField(blank=True, max_length=250)),
                ('dataset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
